
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bbq_development

test:
  <<: *default
  database: bbq_test

production:
  adapter: postgresql
  host: localhost
  port: 5432
  database: bbq_prod
  user: bbq
  password: <%= Rails.application.credentials.dig(:db, :password) %>
